### ISSUE TITLE
Generate array via formula

### ISSUE THREAD

**Issue by upsilon-den** [apollonin/numphp#25]
Can you realize the method, which will generate an array via formula? 
The formula will be an arithmetic or geometric progressions.

e.g.
$arr = Generator::viaFormula($from = 1, $to = 10, '2n+1');
2n+1 - formula.

**Comment by apollonin** [comment]
interesting. I'll see what I can do here.

**Comment by apollonin** [comment]
@seredenko is it smth you wanted? look at pr #29
