### ISSUE TITLE
Generate Fibonacci sequence

### ISSUE THREAD

**Issue by upsilon-den** [apollonin/numphp#26]
Make generator for Fibonacci's sequence.

$arr = Generator::fibo($howMuchElementsWeNeed = 7);
[1, 1, 2, 3, 5, 8, 13]

**Comment by apollonin** [comment]
is this is specific cas of #25 issue? I suppose fibonacci formula could be like `fib`

**Comment by apollonin** [comment]
Added new fib($n) method to Generator class: https://github.com/apollonin/numphp/commit/886d2cde2ce5bae1f0b7bfc6984d249d31acb8fa
