### ISSUE TITLE
Make mask by condition

### ISSUE THREAD

**Issue by upsilon-den** [apollonin/numphp#30]
Can you realize the method, which will be making a mask from an array by some condition?

e.g.

$array = [1,-5,10,-25,3,12];
$array->mask('>0'); => // [true, false, true, false, true, true]

**Comment by apollonin** [comment]
sure, I can tell you more ,it is already implemented =) 

```
$result = $array['> 0'];

// result
[true, false, true, false, true, true]
```


or maybe you meant smth else?

**Comment by upsilon-den** [comment]
Maybe you can make additional method ->mask() with the same functionality for better readability?

**Comment by apollonin** [comment]
In current implementation 'mask' array in returned from several types:

```
$list->gt(5). $list->lt(5), etc
and
$list['>0']
```

you suggest to add mask() alternative only for the latter syntax?

**Comment by upsilon-den** [comment]
yes

**Comment by apollonin** [comment]
@seredenko done: https://github.com/apollonin/numphp/commit/0af645fbf507afc84ffd6741339608380126412a
