### ISSUE TITLE
Multiple warnings with PHP 7.2.3 (Win 7)

### ISSUE THREAD

**Issue by zhurakovskyi** [apollonin/numphp#48]
[output.txt](https://github.com/apollonin/numphp/files/1778389/output.txt)

**Comment by apollonin** [comment]
Yeah, I did not test it on php 7+. I will check it and se what I can do

**Comment by peter279k** [comment]
I think this PR #51 has fixed this issue.

**Comment by apollonin** [comment]
have you tried to test it? If did not have a time yet....

**Comment by peter279k** [comment]
@apollonin, thank you for your reply. The Travis CI build is passed in Ubuntu system.
However, this has not tested in ```Windows 7``` yet.
I think @zhurakovskyi should do this in the latest version :+1: .
I will test this in ```Win 7``` at my available time.

**Comment by apollonin** [comment]
I suppose issue was resolved
