### ISSUE TITLE
Is  there such a method that can merge two or more np_array？

### ISSUE THREAD

**Issue by varichs** [apollonin/numphp#53]

**Comment by apollonin** [comment]
@varichs , good question. 
Currently there is no implemented way to merge np_arrays. What I can suggest as a quick (but not very optimal) solution, is to use native php array_merge method:

```
new np_array(array_merge((array)$array1, (array)$array2))
```

you'll get merged arrays as np_array type.


But I'll add this feature as soon as possible to be able to do it easily and in more optimal way

**Comment by apollonin** [comment]
@varichs I've added concatenation (like array_merge) logic to arrays and matrixes. 
Check new release: https://github.com/apollonin/numphp/releases/tag/1.9.0

Also README was updated with instructions.

Hope that helps.

**Comment by varichs** [comment]
> @varichs I've added concatenation (like array_merge) logic to arrays and matrixes.
> Check new release: https://github.com/apollonin/numphp/releases/tag/1.9.0
> 
> Also README was updated with instructions.
> 
> Hope that helps.

thanks!
